version: "3.3"

services:    
  api:
    build:
      context: .
      dockerfile: ./src/API/Dockerfile
    ports: 
      - 5000:5000

  localstack:
    image: localstack/localstack:0.11.2
    ports:
      - 4566:4566
    volumes:
    - ./test/Api.Tests.Docker/images/localstack/scripts:/docker-entrypoint-initaws.d